version: "3"
services:
#######
# Business 1
#######
  veronas:
    # image: cloud.canister.io:5000/dgateled/business-partner-agent:0.1.7
    image: bpa:latest
    container_name: veronas
    hostname: ${BPA_HOST}
    environment:
      JAVA_OPTS: >
        -Dbpa.acapy.url=${ACAPY_ADMIN_URL}
        -Dbpa.acapy.apiKey=${ACAPY_ADMIN_URL_API_KEY}
        -Dbpa.acapy.bearerToken=${TENANT_TOKEN}
        -Dmicronaut.security.enabled=${BPA_SECURITY_ENABLED}
        -Dmicronaut.server.port=${BPA_PORT}
        -Dmicronaut.config.files=/app/mount/application.yml,/app/mount/security-keycloak.yml,/app/mount/multi-tenancy.yml
        -Dlogback.configurationFile=/app/mount/log4js.xml
        -Dbpa.pg.url=jdbc:postgresql://${DOCKERHOST}:${POSTGRES_PORT}/${POSTGRES_DB}
        -Dbpa.pg.username=${POSTGRES_USER}
        -Dbpa.pg.password=${POSTGRES_PASSWORD}
        -Dbpa.host=${BPA_HOST}
        -Dbpa.scheme=${BPA_SCHEME}
      BPA_LEDGER_BROWSER: ${LEDGER_URL}
      BPA_REDIRECT_URL: ${BPA_REDIRECT_URL}
      TENANCY_ATTRIBUTE_NAME: ${TENANCY_ATTRIBUTE_NAME}
      BPA_WEB_MODE: ${BPA_WEB_MODE}
      BPA_BOOTSTRAP_UN: ${BPA_BOOTSTRAP_UN}
      BPA_BOOTSTRAP_PW: ${BPA_BOOTSTRAP_PW}
      ACAPY_ENDPOINT: ${ACAPY_ENDPOINT}
      AGENT_NAME: ${BPA_SERVICE_NAME}
      BPA_IMPRINT_URL: ${BPA_IMPRINT_URL}
      BPA_PRIVACY_POLICY_URL: ${BPA_PRIVACY_POLICY_URL}
      BPA_CREDDEF_REVOCATION_REGISTRY_SIZE: ${BPA_CREDDEF_REVOCATION_REGISTRY_SIZE}
      TENANT_TOKEN: ${TENANT_TOKEN}
      BPA_WEBHOOK_KEY: ${BPA_WEBHOOK_KEY}
      NODE_ENV: development
      SERVER_HOST: ${BPA_HOST}
      BPA_KEYCLOAK_ROLES_NAME: ${BPA_KEYCLOAK_ROLES_NAME}
      BPA_KEYCLOAK_NAME_KEY: ${BPA_KEYCLOAK_NAME_KEY}
      BPA_KEYCLOAK_REDIRECT_URI: ${BPA_KEYCLOAK_REDIRECT_URI}
      BPA_KEYCLOAK_SCOPES: ${BPA_KEYCLOAK_SCOPES}
      BPA_KEYCLOAK_ISSUER: ${BPA_KEYCLOAK_ISSUER}
      BPA_KEYCLOAK_ENDSESSION_URL: ${BPA_KEYCLOAK_ENDSESSION_URL}
      BPA_KEYCLOAK_VCAUTHN_PRES_REQ_CONF_ID: ${BPA_KEYCLOAK_VCAUTHN_PRES_REQ_CONF_ID}
      BPA_KEYCLOAK_GRANT_TYPE: ${BPA_KEYCLOAK_GRANT_TYPE}
      BPA_SECURITY_ENABLED: ${BPA_SECURITY_ENABLED}
      BPA_KEYCLOAK_ROLES_SEPARATOR: ${BPA_KEYCLOAK_ROLES_SEPARATOR}
      BPA_KEYCLOAK_COOKIE_ENABLED: ${BPA_KEYCLOAK_COOKIE_ENABLED}
      BPA_KEYCLOAK_COOKIE_DOMAIN: ${BPA_KEYCLOAK_COOKIE_DOMAIN}
      BPA_KEYCLOAK_COOKIE_HTTP_ONLY: ${BPA_KEYCLOAK_COOKIE_HTTP_ONLY}
      BPA_KEYCLOAK_COOKIE_SECURE: ${BPA_KEYCLOAK_COOKIE_SECURE}
      BPA_KEYCLOAK_COOKIE_MAX_AGE: ${BPA_KEYCLOAK_COOKIE_MAX_AGE}
      BPA_KEYCLOAK_COOKIE_SAME_SITE: ${BPA_KEYCLOAK_COOKIE_SAME_SITE}
      BPA_KEYCLOAK_COOKIE_PATH: ${BPA_KEYCLOAK_COOKIE_PATH}
      BPA_KEYCLOAK_COOKIE_NAME: ${BPA_KEYCLOAK_COOKIE_NAME}
      BPA_KEYCLOAK_JWS_URL: ${BPA_KEYCLOAK_JWS_URL}
      BPA_KEYCLOAK_SECRET_GENERATOR_JWS_ALGORITHM: ${BPA_KEYCLOAK_SECRET_GENERATOR_JWS_ALGORITHM}
      BPA_KEYCLOAK_SECRET_GENERATOR_SECRET: ${BPA_KEYCLOAK_SECRET_GENERATOR_SECRET}
      BPA_KEYCLOAK_SECRET_GENERATOR_BASE64: ${BPA_KEYCLOAK_SECRET_GENERATOR_BASE64}
      BPA_KEYCLOAK_TOKEN_GENERATOR_TOKEN_EXP: ${BPA_KEYCLOAK_TOKEN_GENERATOR_TOKEN_EXP}
      BPA_KEYCLOAK_OPENID_LOGOUT_URI: ${BPA_KEYCLOAK_OPENID_LOGOUT_URI}
      BPA_KEYCLOAK_OPENID_ENDSESSION_ENABLED: ${BPA_KEYCLOAK_OPENID_ENDSESSION_ENABLED}
      BPA_KEYCLOAK_ENDSESSION_REDIRECT_URI: ${BPA_KEYCLOAK_ENDSESSION_REDIRECT_URI}
      BPA_KEYCLOAK_OPENID_ADDITIONAL_CLAIMS_ACCESS: ${BPA_KEYCLOAK_OPENID_ADDITIONAL_CLAIMS_ACCESS}
      BPA_KEYCLOAK_OPENID_ADDITIONAL_CLAIMS_REFRESH: ${BPA_KEYCLOAK_OPENID_ADDITIONAL_CLAIMS_REFRESH}
      BPA_KEYCLOAK_CLIENT_ID: ${BPA_KEYCLOAK_CLIENT_ID}
      BPA_KEYCLOAK_CLIENT_SECRET: ${BPA_KEYCLOAK_CLIENT_SECRET}
      BPA_KEYCLOAK_TOKEN_URL: ${BPA_KEYCLOAK_TOKEN_URL}
      BPA_KEYCLOAK_AUTH_METHOD: ${BPA_KEYCLOAK_AUTH_METHOD}
      BPA_KEYCLOAK_INTROSPECTION_URL: ${BPA_KEYCLOAK_INTROSPECTION_URL}
      BPA_KEYCLOAK_AUTHORIZATION_URL: ${BPA_KEYCLOAK_AUTHORIZATION_URL}
      BPA_KEYCLOAK_CONFIG_PATH: ${BPA_KEYCLOAK_CONFIG_PATH}
      BPA_KEYCLOAK_JWKS_URI: ${BPA_KEYCLOAK_JWKS_URI}
      BPA_KEYCLOAK_OPENID_RESPONSE_TYPE: ${BPA_KEYCLOAK_OPENID_RESPONSE_TYPE}
      BPA_KEYCLOAK_OPENID_RESPONSE_MODE: ${BPA_KEYCLOAK_OPENID_RESPONSE_MODE}
      BPA_KEYCLOAK_USER_INFO: ${BPA_KEYCLOAK_USER_INFO}
      BPA_AUTHENTICATION_TYPE: ${BPA_AUTHENTICATION_TYPE}
      BPA_KEYCLOAK_OPENID_JWKS_URI: ${BPA_KEYCLOAK_OPENID_JWKS_URI}
      BPA_KEYCLOAK_ADDITIONAL_JWT: ${BPA_KEYCLOAK_ADDITIONAL_JWT}
      BPA_KEYCLOAK_ADDITIONAL_ACCESS_TOKEN: ${BPA_KEYCLOAK_ADDITIONAL_ACCESS_TOKEN}
      BPA_KEYCLOAK_ADDITIONAL_REFRESH_TOKEN: ${BPA_KEYCLOAK_ADDITIONAL_REFRESH_TOKEN}
      BPA_KEYCLOAK_REDIRECTION_BOOLEAN: ${BPA_KEYCLOAK_REDIRECTION_BOOLEAN}
      BPA_KEYCLOAK_REDIRECT_UNAUTHORIZED: ${BPA_KEYCLOAK_REDIRECT_UNAUTHORIZED}
      BPA_KEYCLOAK_SECURITY_ENABLED: ${BPA_KEYCLOAK_SECURITY_ENABLED}
      SERVICE_NAME: ${SERVICE_NAME}
      BPA_KEYCLOAK_LOGOUT_REDIRECT: ${BPA_KEYCLOAK_LOGOUT_REDIRECT}
      VUE_APP_LOGOUT_URL_PATH: ${VUE_APP_LOGOUT_URL_PATH}
      MULTI_TENANCY_COOKIE_NAME: ${MULTI_TENANCY_COOKIE_NAME}
      DATABASE_SCHEMA: ${DATABASE_SCHEMA}
      # VUE_APP_LOGOUT_URL_PATH: ${VUE_APP_LOGOUT_URL_PATH}
    ports:
      - ${BPA_PORT}:${BPA_PORT}
      - ${BPA_DEBUG_PORT}:${BPA_DEBUG_PORT}
    restart: always
    # command:
    #   - /bin/bash
    #   - -c
    #   - |
    #     ls /app/mount
    #     # cat application.yml
    #     # java -XX:+UnlockExperimentalVMOptions -Dcom.sun.management.jmxremote ${JAVA_OPTS} -jar business-partner-agent.jar
    # volumes:
    # - ./mount/:/app
    volumes:
    - ./mount/:/app/mount/
    
