version: "3"
services:
#######
# Business 1
#######
  second-db:
    image: "postgres:12-alpine"
    container_name: second-db
    hostname: second-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=${POSTGRES_DB}
      # - POSTGRESQL_ADMIN_PASSWORD=${POSTGRESQL_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    # volumes:
    #   # - /home/omoge_real/mnt/11-verona-apartments-db:/var/lib/postgresql/data
    #   - /home/omoge_real/new-db:/var/lib/postgresql/data
